sync with master site

diff --git a/bin/multicrop b/bin/multicrop
--- a/bin/multicrop
+++ b/bin/multicrop
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Revised by Fred Weinhaus ...................... revised 1/21/2017
+# Revised by Fred Weinhaus ...................... revised 10/15/2019
 # Revised by Anthony Thyssen to add -b option ... revised 8/24/2010
 # Developed by Fred Weinhaus 1/30/2010 .......... revised 4/25/2015
 #
@@ -29,7 +29,8 @@
 ####
 #
 # USAGE: multicrop [-c coords] [-b bcolor] [-f fuzzval] [-g grid] [-d discard] 
-# [-p prune] [-u unrotate] [-e extend] [-m mask] infile outfile
+# [-p prune] [-u unrotate] [i innertrim] [-e extend] [-m mask] [-r resize] [-D density] 
+# infile outfile
 # USAGE: multicrop [-h or -help]
 # 
 # OPTIONS:
@@ -54,11 +55,16 @@
 # -u          unrotate       unrotate method; choices are 1 for -deskew, 
 #                            2 for unrotate script and 3 for no unrotate;
 #                            default=1
-# -e          extend         extend crop on each side in pixels; does not work 
-#                            work with option -u 2; integer>=0; default=0  
+# -i          innertrim      trims inside the cropped area to an orthogonal 
+#                            rectangle; yes or no; default=no      
+# -e          extend         extend crop on each side in pixels; integer; default=0  
 # -m          mask           mask presentation method; choices are view, 
 #                            save (to file) or output mask only; default 
 #                            is none of the above, just output the images
+# -r          resize         resize percent to scale the image down; float>0;  
+#                            default is no resizing.
+# -D          density        density to use when reading a single page of a PDF; 
+#                            integer>0; default is no assigned density
 # 
 ###
 # 
@@ -95,8 +101,9 @@
 # 
 # -b bcolor ... BCOLOR is the background color to use for flood fill instead 
 # of extracting this color from the image. This is useful when an image has 
-# no borders with sub-images hard against the edges. Any valid IM color is 
-# allowed. The default is to use option -c.
+# no borders so that the sub-images are hard against the edges. The bcolor 
+# will be used to put a one pixel border around the image and coords will be 
+# set to 0,0. Any valid IM color is allowed. The default is to use option -c.
 # 
 # -f fuzzval ... FUZZVAL is the fuzz amount specified as an integer percent
 # value between 0 to 100 (without the % sign). The correct choice of fuzz
@@ -118,17 +125,23 @@
 # morphologic disk shape operations of the specified prune size. Values are 
 # integer>1 (which will later be divided by 2). The default is no pruning.  
 # 
-# -u unrotate ... UNROTATE is the unrotation method. Choices are: 1, 2 or 3.
+# -u unrotate ... UNROTATE is the unrotation method. Choices are: 1, 2, 3 or 4.
 # The default is unrotate=1, which is fast and uses the IM -deskew function, 
 # but is limited to images that are rotated no more than 5 degrees in the scan. 
 # Option unrotate=2 uses my unrotate script. It can handle larger rotations, 
 # but is slower. If using the latter method, my unrotate script must be 
 # downloaded and also installed so that it is available for this script to use.
-# Option unrotate=3 makes no attempt to unrotate the images.
+# Option unrotate=3 makes no attempt to unrotate the images. Option unrotate=4 
+# uses my script, autotrim, to do an inner crop to a rectangle.
+# 
+# -i innertrim ... INNERTRIM trims inside the cropped area to an orthogonal 
+# rectangle. Requires my script, autotrim. The choices are: yes or no. 
+# The default=no.
 # 
 # -e extend ... EXTEND crop on each side for the output images in pixels. 
-# The extended region will come from the background of the image. This does 
-# not work work with option -u 2. Values are integers>=0. The default=0.
+# The extended region will come from the background of the image. Values are integers. 
+# Positive makes the results larger. Negative makes the results smaller. Positive 
+# values are only allowed for unrotate=3 (no unrotation) and innertrim=no. The default=0.
 # 
 # -m mask ... MASK provides several options for reviewing the initial mask that 
 # is generated by the fuzz value. The choices are: view (display to X11 window),
@@ -141,8 +154,17 @@
 # images, but the background can "eat" a little into the images so long as no 
 # full edge is lost or the images is split into multiple parts.
 # 
-# NOTE: If using unrotate method 2, then my script, unrotate, is required 
-# as well.
+# -r resize ... RESIZE amount in percent to scale the image down. Values are floats>0.  
+# The default is no resizing. This is useful to improve speed and floodfilling 
+# when you have a large image, especially if the background is grainy. Note: do not 
+# include the % symbol.
+#
+# -D density ... DENSITY to use when reading a single page of a PDF. Multipage pdf 
+# files are not permitted. Values are integers>0. The default is no assigned density.
+# 
+# REQUIREMENTS: 
+# If using unrotate method 2, then my script, unrotate, is required. 
+# If using innertrim, then my script, autotrim is required.
 # 
 # CAVEAT: No guarantee that this script will work on all platforms, 
 # nor that trapping of inconsistent parameters is complete and 
@@ -161,6 +183,9 @@ prune=""				# prune out noise in mask
 extend=0				# extend the output crop on all sides
 mask=""					# view, save, output
 unrotate=1				# 1=deskew 2=unrotate
+innertrim="no"			# trim inside cropped area to orthogonal rectangle
+resize=""				# resize percent
+density=""				# density to use for input PDF
 debug="false"
 
 # set directory for temporary files
@@ -207,7 +232,7 @@ if [ $# -eq 0 ]
 	echo ""
 	usage2
 	exit 0
-elif [ $# -gt 20 ]
+elif [ $# -gt 26 ]
 	then
 	errMsg "--- TOO MANY ARGUMENTS WERE PROVIDED ---"
 else
@@ -280,9 +305,9 @@ else
 				   shift  # to get the next parameter
 				   # test if parameter starts with minus sign 
 				   errorMsg="--- INVALID EXTEND SPECIFICATION ---"
-				   checkMinus "$1"
-				   extend=`expr "$1" : '\([0-9]*\)'`
-				   [ "$extend" = "" ] && errMsg "--- EXTEND=$extend MUST BE A NON-NEGATIVE INTEGER VALUE (with no sign) ---"
+				   #checkMinus "$1"
+				   extend=`expr "$1" : '\([-0-9]*\)'`
+				   [ "$extend" = "" ] && errMsg "--- EXTEND=$extend MUST BE AN INTEGER VALUE (with no sign) ---"
 				   ;;
 			-u)    # unrotate
 				   shift  # to get the next parameter
@@ -290,7 +315,20 @@ else
 				   errorMsg="--- INVALID UNROTATE SPECIFICATION ---"
 				   checkMinus "$1"
 				   unrotate=`expr "$1" : '\([0-9]\)'`
-				   [ $unrotate -lt 1 -a $unrotate -gt 3 ] && errMsg "--- UNROTATE=$unrotate MUST BE EITHER 1, 2 OR 3 ---"
+				   [ $unrotate -lt 1 -a $unrotate -gt 3 ] && errMsg "--- UNROTATE=$unrotate MUST BE EITHER 1, 2, 3 OR 4 ---"
+				   ;;
+			-i)    # get innertrim
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID INNERTRIM SPECIFICATION ---"
+				   checkMinus "$1"
+				   innertrim="$1"
+				   innertrim=`echo "$innertrim" | tr "[:upper:]" "[:lower:]"`
+				   case "$innertrim" in 
+						yes|y) innertrim="yes" ;;
+						no|n) innertrim="no" ;;
+						*) errMsg "--- INNERTRIM=$innertrim IS AN INVALID VALUE ---" 
+					esac
 				   ;;
 			-m)    # mask
 				   shift  # to get the next parameter
@@ -299,6 +337,26 @@ else
 				   checkMinus "$1"
 				   mask=`echo "$1" | tr "[:upper:]" "[:lower:]"`
 				   [ "$mask" != "view" -a "$mask" != "save" -a "$mask" != "output"  ] && errMsg "--- MASK=$mask MUST BE EITHER VIEW, SAVE OR OUTPUT ---"
+				   ;;
+			-r)    # resize
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID RESIZE SPECIFICATION ---"
+				   checkMinus "$1"
+				   resize=`expr "$1" : '\([.0-9]*\)'`
+				   [ "$resize" = "" ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE (with no sign) ---"
+				   testA=`echo "$resize == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE GREATER THAN 0 ---"
+				   ;;
+			-D)    # density
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID DENSITY SPECIFICATION ---"
+				   checkMinus "$1"
+				   density=`expr "$1" : '\([0-9]*\)'`
+				   [ "$density" = "" ] && errMsg "--- DENSITY=$density MUST BE A NON-NEGATIVE INTEGER VALUE (with no sign) ---"
+				   testA=`echo "$density == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- DENSITY=$density MUST BE A NON-NEGATIVE INTEGER VALUE GREATER THAN 0 ---"
 				   ;;
 			 -)    # STDIN and end of arguments
 				   break
@@ -318,17 +376,28 @@ else
 fi
 
 # test if both bcolor and coords specified at the same time
-if [ "X$bcolor" != "X" -a "X$coords" != "X" ]; then
+if [ "$bcolor" != "" -a "$coords" != "" ]; then
   errMsg "--- BACKGROUND COLOR AND COODINATES CAN NOT BE USED TOGETHER ---"
-elif [ "X$bcolor" = "X" -a "X$coords" = "X" ]; then
+elif [ "$bcolor" = "" -a "$coords" = "" ]; then
 	coords="0,0"
 fi
+
 
 # test that infile provided
 [ "$infile" = "" ] && errMsg "NO INPUT FILE SPECIFIED"
 
 # test that outfile provided
 [ "$outfile" = "" ] && errMsg "NO OUTPUT FILE SPECIFIED"
+
+# test if input is single layer/page/frame
+count=`convert -ping "$infile" -format "%m\n" info: | wc -l`
+[ $count -gt 1 ] && errMsg "--- MULTIPAGE/MULTIFRAME/MULTILAYER IMAGES ARE NOT ALLOWED ---"
+
+if [ "$density" != "" ]; then
+	dproc="-density $density"
+else
+	dproc=""
+fi
 
 # set up temp file
 tmpA1="$dir/multicrop_1_$$.mpc"
@@ -339,21 +408,28 @@ tmpA3="$dir/multicrop_3_$$.mpc"
 tmpB3="$dir/multicrop_3_$$.cache"
 tmpA4="$dir/multicrop_4_$$.mpc"
 tmpB4="$dir/multicrop_4_$$.cache"
-tmpA5="$dir/multicrop_5_$$.mpc"
-tmpB5="$dir/multicrop_5_$$.cache"
+tmpA5="$dir/multicrop_5_$$.miff"
+tmpA6="$dir/multicrop_6_$$.mpc"
+tmpB6="$dir/multicrop_6_$$.cache"
 
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB5;" 0
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB5; exit 1" 1 2 3 15
-#trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB5; exit 1" ERR
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB6 $tmpA6;" 0
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5 $tmpB6 $tmpA6; exit 1" 1 2 3 15
+#trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB3 $tmpA4 $tmpB4 $tmpA5; exit 1" ERR
 
 # read the input image into the temp files and test validity.
-convert -quiet "$infile" +repage "$tmpA1" ||
-	errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+if [ "$resize" != "" ]; then
+	convert -quiet $dproc "$infile" +repage "$tmpA6" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+	convert "$tmpA6" -resize $resize% "$tmpA1"
+else
+	convert -quiet $dproc "$infile" +repage "$tmpA1" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+fi
 
 
 # get im_version
 im_version=`convert -list configure | \
-	sed '/^LIB_VERSION_NUMBER /!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
+	sed '/^LIB_VERSION_NUMBER */!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
 
 # get output filename and suffix
 outnameArr=(`echo "$outfile" | sed -n 's/^\(.*\)[.]\([^.]*\)$/\1 \2/p'`)
@@ -362,15 +438,45 @@ suffix="${outnameArr[1]}"
 #echo "outname=$outname"
 #echo "suffix=$suffix"
 
-# get image width and height
-width=`identify -ping -format "%w" $tmpA1`
-height=`identify -ping -format "%h" $tmpA1`
+if [ "$im_version" -ge "07000000" ]; then
+	identifying="magick identify"
+else
+	identifying="identify"
+fi
 
+# get image width and height
+width=`$identifying -ping -format "%w" $tmpA1`
+height=`$identifying -ping -format "%h" $tmpA1`
+
+# test for extend
+test=`convert xc: -format "%[fx:$extend>0?1:0]" info:`
+[ $test -eq 1 -a $unrotate -ne 3 ] && errMsg "--- SIGN FOR EXTEND=$extend MUST BE NEGATIVE ---"
+[ $test -eq 1 -a $unrotate -eq 3 -a "$innertrim" = "yes" ] && errMsg "--- SIGN FOR EXTEND=$extend MUST BE NEGATIVE ---"
+
+
+# test if coords provided as x,y
+# coords="" if test fails and have other characters such as northwest
+coords1=`expr "$coords" : '\([0-9]*,[0-9]*\)'`
 
 # get color at user specified location
-if [ "X$bcolor" != "X" ]; then
+if [ "$bcolor" != "" ]; then
 	coords="0,0"
-else
+elif [ "$coords1" != "" -a "$resize" != "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	x=`convert xc: -format "%[fx:round($x*$resize/100)]" info:`
+	y=`convert xc: -format "%[fx:round($y*$resize/100)]" info:`
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" != "" -a "$resize" = "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	# account for pad of 1
+	x=$((x+1))	
+	y=$((y+1))	
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" = "" ]; then
 	widthm1=`convert xc: -format "%[fx:$width-1]" info:`
 	heightm1=`convert xc: -format "%[fx:$height-1]" info:`
 	midwidth=`convert xc: -format "%[fx:round(($width-1))/2]" info:`
@@ -385,7 +491,6 @@ else
 		s|south)         coords="$midwidth,$heightm1" ;;
 		sw|southwest)    coords="0,$heightm1" ;;
 		w|west)          coords="0,$midheight" ;;
-		[0-9]*,[0-9]*)   coords=$coords ;;
 		*)  errMsg "--- INVALID COORDS ---" ;;
 	esac
 	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
@@ -394,8 +499,8 @@ fi
 
 
 # get grid spacing
-wg=`convert xc: -format "%[fx:round($grid*$width/100)]" info:`
-hg=`convert xc: -format "%[fx:round($grid*$height/100)]" info:`
+wg=`convert xc: -format "%[fx:round(($grid/100)*$width)]" info:`
+hg=`convert xc: -format "%[fx:round(($grid/100)*$height)]" info:`
 num=`convert xc: -format "%[fx:round(100/$grid) - 2]" info:`
 #echo "width=$width; height=$height; wg=$wg; hg=$hg; num=$num"
 
@@ -417,7 +522,7 @@ fi
 
 # add a border, and flood fill from all edges inward
 convert $tmpA1 -fuzz ${fuzzval}% -fill none \
-	-bordercolor $bcolor -border 1x1 \
+	-bordercolor "$bcolor" -border 1x1 \
 	-draw "$matte_alpha $coords floodfill" \
 	-shave 1x1 -fill red +opaque none \
 	-background black -alpha background \
@@ -435,9 +540,7 @@ fi
 
 # set up for unrotate 1 or 3
 if [ $unrotate -eq 1 ]; then
-	derotate="-deskew 40%"
-elif [ $unrotate -eq 3 ]; then
-	derotate=""
+	derotate="-background $bcolor -deskew 40%"
 fi
 
 
@@ -474,41 +577,54 @@ for ((j=0;j<=$num;j++))
 			# areas eaten away are filled with white.
 			# Note flatten uses the virtual canvas left by -trim so that it 
 			# goes back into the right location.
-			convert \( $tmpA3 -channel rgba -alpha on \
-				-fill none +opaque white -alpha off \) \
-				\( +clone -trim -fill white -opaque black -write $tmpA5 \) \
-				-flatten $tmpA4
-			# Print size and page geometry
-			wd=`identify -ping -format "%w" $tmpA5`
-			ht=`identify -ping -format "%h" $tmpA5`
-			pg=`identify -ping -format "%g" $tmpA5`
+			convert $tmpA3 -channel rgba -alpha on \
+				-fill none +opaque white -alpha off \
+				-trim -fill white -opaque black $tmpA4
+
+			# get size and offset
+			wd=`$identifying -ping -format "%w" $tmpA4`
+			ht=`$identifying -ping -format "%h" $tmpA4`
+			pg=`$identifying -ping -format "%g" $tmpA4`
 			offx=`echo $pg | cut -d+ -f2`
 			offy=`echo $pg | cut -d+ -f3`
-			echo "Size: ${wd}x${ht}"  
-			echo "Page Geometry: $pg"
-			echo "offx=$offx; offy=$offy;"
+			if [ "$resize" != "" ]; then
+				wd=`convert xc: -format "%[fx:round($wd*100/$resize)+2*$extend]" info:`
+				ht=`convert xc: -format "%[fx:round($ht*100/$resize)+2*$extend]" info:`
+				offx=`convert xc: -format "%[fx:round($offx*100/$resize)-$extend]" info:`
+				offy=`convert xc: -format "%[fx:round($offy*100/$resize)-$extend]" info:`
+				img=$tmpA6
+			else
+				wd=$((wd+2*extend))
+				ht=$((ht+2*extend))
+				offx=$((offx-extend))
+				offy=$((offy-extend))
+				img=$tmpA1
+			fi
+#			echo "Size: ${wd}x${ht}"  
+#			echo "Page Geometry: $pg"
+#			echo "offx=$offx; offy=$offy;"
+			echo "Initial Crop Box: ${wd}x${ht}+${offx}+${offy}"
 			echo ""
 			# Composite the black and white mask onto the original scan.
 			# Then trim and deskew/unrotate to make the output.
-			if [ $unrotate -eq 1 -o $unrotate -eq 3 ]; then
-				if [ $extend -eq 0 ]; then
-					convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage $derotate \
-						-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage \
-						${outname}-${kk}.${suffix}
-				else
-					wd=$((wd+2*extend))
-					ht=$((ht+2*extend))
-					offx=$((offx-extend))
-					offy=$((offy-extend))
-					convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage \
-						-background "$bcolor" $derotate \
-						${outname}-${kk}.${suffix}
-				fi
+			if [ $unrotate -eq 3 ]; then
+				convert $img -crop ${wd}x${ht}+${offx}+${offy} +repage $tmpA5
+			elif [ $unrotate -eq 1 ]; then
+				convert $img -crop ${wd}x${ht}+${offx}+${offy} +repage $derotate \
+					-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage $tmpA5
 			elif [ $unrotate -eq 2 ]; then
-				convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage  \
+				convert $img -crop ${wd}x${ht}+${offx}+${offy} +repage \
 					-fuzz ${fuzzval}% -trim miff:- | \
-					unrotate -f ${fuzzval}% - "${outname}-${kk}.${suffix}"
+					unrotate -C "$bcolor" -f ${fuzzval}% - $tmpA5
 			fi
+			if [ "$innertrim" = "yes" ]; then
+				mextend=-$extend
+				autotrim -m inner -f $fuzzval -C "$bcolor" -l $mextend -t $mextend \
+					-r $extend -b $extend $tmpA5 ${outname}-${kk}.${suffix}
+			else
+				convert $tmpA5 ${outname}-${kk}.${suffix}
+			fi
+
 			# Fill the selected photo area in the red/none mask with none 
 			# for use with next coordinate so that it does not find it again.
 			convert $tmpA3 -channel rgba -alpha on -fill none -opaque white $tmpA2
diff --git a/bin/multicrop2 b/bin/multicrop2
--- a/bin/multicrop2
+++ b/bin/multicrop2
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Developed by Fred Weinhaus 12/30/2015 .......... revised 12/30/2015
+# Developed by Fred Weinhaus 12/30/2015 .......... revised 1/4/2020
 #
 # ------------------------------------------------------------------------------
 # 
@@ -27,8 +27,8 @@
 ####
 #
 # USAGE: multicrop2 [-c coords] [-b bcolor] [-f fuzzval] [-d discard] 
-# [-u unrotate] [-e extend] [-m mask] [-t threshold] [-s showstats] 
-# infile outfile
+# [-u unrotate] [-i innertrim] [-e extend] [-m mask] [-t threshold] 
+# [-r resize] [-D density] [-S sortval] [-s showstats] [-v vc] infile outfile
 # USAGE: multicrop [-h or -help]
 # 
 # OPTIONS:
@@ -44,15 +44,26 @@
 #                      this size; integer>0; default is to keep all
 # -u     unrotate      unrotate method; choices are 1 for -deskew, 2 for 
 #                      unrotate script and 3 for no unrotate; default=1
-# -e     extend        extend crop on each side in pixels; does not work 
-#                      work with option -u 2; integer>=0; default=0  
+# -i     innertrim     trims inside the cropped area to an orthogonal rectangle;
+#                      yes or no; default=no      
+# -e     extend        extend crop on each side in pixels; integer; default=0  
 # -m     mask          mask presentation method; choices are view, 
 #                      save (to file) or output mask only; default 
 #                      is none of the above, just output the images
 # -t     threshold     threshold on number of objects; aborts if more than 
 #                      threshold number of objects are detected; integer>0; 
 #                      default is no abort and keep all objects.
+# -r     resize        resize percent to scale the image down; float>0;  
+#                      default is no resizing.
+# -D     density       density to use when reading a single page of a PDF; 
+#                      integer>0; default is no assigned density
+# -S     sortval       sort regions by upper left bounding box x,y coordinates 
+#                      rounded to the specified positive integer increment; 
+#                      default is no sorting
 # -s     showstats     show connected components stats; yes or no; default=no
+# -v                   keep virtual canvas; default is not to keep virtual canvas; 
+#                      only valid for -u=3 (no unrotate) and for output format that 
+#                      supports virtual canvas such as PNG or TIFF.
 # 
 ###
 # 
@@ -89,8 +100,9 @@
 # 
 # -b bcolor ... BCOLOR is the background color to use for flood fill instead 
 # of extracting this color from the image. This is useful when an image has 
-# no borders with sub-images hard against the edges. Any valid IM color is 
-# allowed. The default is to use option -c.
+# no borders so that the sub-images are hard against the edges. The bcolor 
+# will be used to put a one pixel border around the image and coords will be 
+# set to 0,0. Any valid IM color is allowed. The default is to use option -c.
 # 
 # -f fuzzval ... FUZZVAL is the fuzz amount specified as an integer percent
 # value between 0 to 100 (without the % sign). The correct choice of fuzz
@@ -112,9 +124,14 @@
 # is available for this script to use. Option unrotate=3 makes no attempt to 
 # unrotate the images.
 # 
+# -i innertrim ... INNERTRIM trims inside the cropped area to an orthogonal 
+# rectangle. Requires my script, autotrim. The choices are: yes or no. 
+# The default=no.
+#
 # -e extend ... EXTEND crop on each side for the output images in pixels. 
-# The extended region will come from the background of the image. This does 
-# not work work with option -u 2. Values are integers>=0. The default=0.
+# The extended region will come from the background of the image. Values are integers. 
+# Positive makes the results larger. Negative makes the results smaller. Positive 
+# values are only allowed for unrotate=3 (no unrotation) and innertrim=no. The default=0.
 # 
 # -m mask ... MASK provides several options for reviewing the initial mask that 
 # is generated by the fuzz value. The choices are: view (display to X11 window),
@@ -132,13 +149,28 @@
 # integers greater than 0. The default is no abort and keep all objects. 
 # To avoid an abort, use the -d discard option. 
 # 
+# -r resize ... RESIZE amount in percent to scale the image down. Values are floats>0.  
+# The default is no resizing. This is useful to improve speed and floodfilling 
+# when you have a large image, especially if the background is grainy. Note: do not 
+# include the % symbol.
+#
+# -D density ... DENSITY to use when reading a single page of a PDF. Multipage pdf 
+# files are not permitted. Values are integers>0. The default is no assigned density.
+# 
+# -S sortval ... SORT regions by their upper left bounding box x,y coordinates 
+# rounded to the specified positive integer increment. The default is 
+# no sorting.
+#                      
 # -s showstats ... SHOWSTATS shows the connected components statistics. 
 # Choices are: yes (y) or no (n). The default=no.
 # 
-# NOTE: If using unrotate method 2, then my script, unrotate, is required 
-# as well.
+# -v ... keep VIRTUAL CANVAS. The default is not to keep virtual canvas. This option  
+# is only valid for -u=3 (no unrotate) and for output format that supports virtual 
+# canvas such as PNG or TIFF.
 # 
 # REQUIREMENTS: IM 6.8.9.10 due to the use of -connected-components.
+# If using unrotate method 2, then my script, unrotate, is required. 
+# If using innertrim, then my script, autotrim is required.
 # 
 # CAVEAT: No guarantee that this script will work on all platforms, 
 # nor that trapping of inconsistent parameters is complete and 
@@ -156,7 +188,12 @@ extend=0				# extend the output crop on all sides
 mask=""					# view, save, output
 threshold=""			# threshold on number of objects; if larger, then abort
 unrotate=1				# 1=deskew 2=unrotate
+innertrim="no"			# trim inside cropped area to orthogonal rectangle
+resize=""				# resize percent
+density=""				# density to use for input PDF
+sortval=""
 showstats="no"          # show CCL stats
+vc="no"					# keep virtual canvas
 debug="false"
 
 # set directory for temporary files
@@ -203,7 +240,7 @@ if [ $# -eq 0 ]
 	echo ""
 	usage2
 	exit 0
-elif [ $# -gt 20 ]
+elif [ $# -gt 29 ]
 	then
 	errMsg "--- TOO MANY ARGUMENTS WERE PROVIDED ---"
 else
@@ -255,9 +292,9 @@ else
 				   shift  # to get the next parameter
 				   # test if parameter starts with minus sign 
 				   errorMsg="--- INVALID EXTEND SPECIFICATION ---"
-				   checkMinus "$1"
-				   extend=`expr "$1" : '\([0-9]*\)'`
-				   [ "$extend" = "" ] && errMsg "--- EXTEND=$extend MUST BE A NON-NEGATIVE INTEGER VALUE (with no sign) ---"
+				   #checkMinus "$1"
+				   extend=`expr "$1" : '\([-0-9]*\)'`
+				   [ "$extend" = "" ] && errMsg "--- EXTEND=$extend MUST BE AN INTEGER VALUE (with no sign) ---"
 				   ;;
 			-u)    # unrotate
 				   shift  # to get the next parameter
@@ -265,7 +302,20 @@ else
 				   errorMsg="--- INVALID UNROTATE SPECIFICATION ---"
 				   checkMinus "$1"
 				   unrotate=`expr "$1" : '\([0-9]\)'`
-				   [ $unrotate -lt 1 -a $unrotate -gt 3 ] && errMsg "--- UNROTATE=$unrotate MUST BE EITHER 1, 2 OR 3 ---"
+				   [ $unrotate -lt 1 -a $unrotate -gt 3 ] && errMsg "--- UNROTATE=$unrotate MUST BE EITHER 1, 2, 3 OR 4 ---"
+				   ;;
+			-i)    # get innertrim
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID INNERTRIM SPECIFICATION ---"
+				   checkMinus "$1"
+				   innertrim="$1"
+				   innertrim=`echo "$innertrim" | tr "[:upper:]" "[:lower:]"`
+				   case "$innertrim" in 
+						yes|y) innertrim="yes" ;;
+						no|n) innertrim="no" ;;
+						*) errMsg "--- INNERTRIM=$innertrim IS AN INVALID VALUE ---" 
+					esac
 				   ;;
 			-m)    # mask
 				   shift  # to get the next parameter
@@ -285,6 +335,35 @@ else
 				   testA=`echo "$threshold < 1" | bc`
 				   [ $testA -eq 1 ] && errMsg "--- THRESHOLD=$threshold MUST BE A NON-NEGATIVE INTEGER VALUE GREATER THAN 0 ---"
 				   ;;
+			-r)    # resize
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID RESIZE SPECIFICATION ---"
+				   checkMinus "$1"
+				   resize=`expr "$1" : '\([.0-9]*\)'`
+				   [ "$resize" = "" ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE (with no sign) ---"
+				   testA=`echo "$resize == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- RESIZE=$resize MUST BE A NON-NEGATIVE FLOAT VALUE GREATER THAN 0 ---"
+				   ;;
+			-D)    # density
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID DENSITY SPECIFICATION ---"
+				   checkMinus "$1"
+				   density=`expr "$1" : '\([0-9]*\)'`
+				   [ "$density" = "" ] && errMsg "--- DENSITY=$density MUST BE A NON-NEGATIVE INTEGER VALUE (with no sign) ---"
+				   testA=`echo "$density == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- DENSITY=$density MUST BE A NON-NEGATIVE INTEGER VALUE GREATER THAN 0 ---"
+				   ;;
+			-S)    # sortval
+				   shift  # to get the next parameter
+				   # test if parameter starts with minus sign 
+				   errorMsg="--- INVALID SORTVAL SPECIFICATION ---"
+				   checkMinus "$1"
+				   sortval=`expr "$1" : '\([0-9]*\)'`
+				   testA=`echo "$sortval == 0" | bc`
+				   [ $testA -eq 1 ] && errMsg "--- SORTVAL=$sortval MUST BE AN INTEGER VALUE GREATER THAN 0 ---"
+				   ;;
 			-s)    # showstats
 				   shift  # to get the next parameter
 				   # test if parameter starts with minus sign 
@@ -292,6 +371,9 @@ else
 				   checkMinus "$1"
 				   showstats=`echo "$1" | tr "[:upper:]" "[:lower:]"`
 				   [ "$showstats" != "yes" -a "$showstats" != "no" ] && errMsg "--- SHOWSTATS=$showstats MUST BE EITHER YES OR NO ---"
+				   ;;
+			-v)    # vc
+				   vc="yes"
 				   ;;
 			 -)    # STDIN and end of arguments
 				   break
@@ -311,9 +393,9 @@ else
 fi
 
 # test if both bcolor and coords specified at the same time
-if [ "X$bcolor" != "X" -a "X$coords" != "X" ]; then
+if [ "$bcolor" != "" -a "$coords" != "" ]; then
   errMsg "--- BACKGROUND COLOR AND COODINATES CAN NOT BE USED TOGETHER ---"
-elif [ "X$bcolor" = "X" -a "X$coords" = "X" ]; then
+elif [ "$bcolor" = "" -a "$coords" = "" ]; then
 	coords="0,0"
 fi
 
@@ -323,24 +405,43 @@ fi
 # test that outfile provided
 [ "$outfile" = "" ] && errMsg "NO OUTPUT FILE SPECIFIED"
 
-# set up temp file
-tmpA1="$dir/multicrop_1_$$.mpc"
-tmpB1="$dir/multicrop_1_$$.cache"
-tmpA2="$dir/multicrop_2_$$.mpc"
-tmpB2="$dir/multicrop_2_$$.cache"
+# test if input is single layer/page/frame
+count=`convert -ping "$infile" -format "%m\n" info: | wc -l`
+[ $count -gt 1 ] && errMsg "--- MULTIPAGE/MULTIFRAME/MULTILAYER IMAGES ARE NOT ALLOWED ---"
 
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2;" 0
-trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2; exit 1" 1 2 3 15
-#trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2; exit 1" ERR
+if [ "$density" != "" ]; then
+	dproc="-density $density"
+else
+	dproc=""
+fi
+
+# set up temp file
+tmpA1="$dir/multicrop2_1_$$.mpc"
+tmpB1="$dir/multicrop2_1_$$.cache"
+tmpA2="$dir/multicrop2_2_$$.mpc"
+tmpB2="$dir/multicrop2_2_$$.cache"
+tmpA3="$dir/multicrop2_3_$$.miff"
+tmpA4="$dir/multicrop2_4_$$.mpc"
+tmpB4="$dir/multicrop2_4_$$.cache"
+
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB4 $tmpA4;" 0
+trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3 $tmpB4 $tmpA4; exit 1" 1 2 3 15
+#trap "rm -f $tmpA1 $tmpB1 $tmpA2 $tmpB2 $tmpA3; exit 1" ERR
 
 # read the input image into the temp files and test validity.
-convert -quiet "$infile" +repage "$tmpA1" ||
-	errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+if [ "$resize" != "" ]; then
+	convert -quiet $dproc "$infile" +repage "$tmpA4" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+	convert "$tmpA4" -scale $resize% "$tmpA1"
+else
+	convert -quiet $dproc "$infile" +repage "$tmpA1" ||
+		errMsg "--- FILE $infile1 DOES NOT EXIST OR IS NOT AN ORDINARY FILE, NOT READABLE OR HAS ZERO SIZE  ---"
+fi
 
 
 # get im_version
 im_version=`convert -list configure | \
-	sed '/^LIB_VERSION_NUMBER /!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
+	sed '/^LIB_VERSION_NUMBER */!d; s//,/;  s/,/,0/g;  s/,0*\([0-9][0-9]\)/\1/g' | head -n 1`
 
 # get output filename and suffix
 outnameArr=(`echo "$outfile" | sed -n 's/^\(.*\)[.]\([^.]*\)$/\1 \2/p'`)
@@ -349,15 +450,44 @@ suffix="${outnameArr[1]}"
 #echo "outname=$outname"
 #echo "suffix=$suffix"
 
-# get image width and height
-width=`identify -ping -format "%w" $tmpA1`
-height=`identify -ping -format "%h" $tmpA1`
+if [ "$im_version" -ge "07000000" ]; then
+	identifying="magick identify"
+else
+	identifying="identify"
+fi
 
+# get image width and height
+width=`$identifying -ping -format "%w" $tmpA1`
+height=`$identifying -ping -format "%h" $tmpA1`
+
+# test for extend
+test=`convert xc: -format "%[fx:$extend>0?1:0]" info:`
+[ $test -eq 1 -a $unrotate -ne 3 ] && errMsg "--- SIGN FOR EXTEND=$extend MUST BE NEGATIVE ---"
+[ $test -eq 1 -a $unrotate -eq 3 -a "$innertrim" = "yes" ] && errMsg "--- SIGN FOR EXTEND=$extend MUST BE NEGATIVE ---"
+
+# test if coords provided as x,y
+# coords="" if test fails and have other characters such as northwest
+coords1=`expr "$coords" : '\([0-9]*,[0-9]*\)'`
 
 # get color at user specified location
-if [ "X$bcolor" != "X" ]; then
+if [ "$bcolor" != "" ]; then
 	coords="0,0"
-else
+elif [ "$coords1" != "" -a "$resize" != "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	x=`convert xc: -format "%[fx:round($x*$resize/100)]" info:`
+	y=`convert xc: -format "%[fx:round($y*$resize/100)]" info:`
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" != "" -a "$resize" = "" ]; then
+	x=`echo "$coords1" | cut -d, -f1`
+	y=`echo "$coords1" | cut -d, -f2`
+	# account for pad of 1
+	x=$((x+1))	
+	y=$((y+1))	
+	coords="$x,$y"
+	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
+elif [ "$coords1" = "" ]; then
 	widthm1=`convert xc: -format "%[fx:$width-1]" info:`
 	heightm1=`convert xc: -format "%[fx:$height-1]" info:`
 	midwidth=`convert xc: -format "%[fx:round(($width-1))/2]" info:`
@@ -372,7 +502,6 @@ else
 		s|south)         coords="$midwidth,$heightm1" ;;
 		sw|southwest)    coords="0,$heightm1" ;;
 		w|west)          coords="0,$midheight" ;;
-		[0-9]*,[0-9]*)   coords=$coords ;;
 		*)  errMsg "--- INVALID COORDS ---" ;;
 	esac
 	bcolor=`convert $tmpA1 -format "%[pixel:u.p{$coords}]" info:`
@@ -405,7 +534,7 @@ fi
 
 # set up for unrotate 1 or 3
 if [ $unrotate -eq 1 ]; then
-	derotate="-deskew 40%"
+	derotate="-background $bcolor -deskew 40%"
 elif [ $unrotate -eq 3 ]; then
 	derotate=""
 fi
@@ -424,10 +553,42 @@ data=`convert $tmpA2 \
 	$discarding -connected-components 4 null:`
 [ "$showstats" = "yes" ] && echo "$data"
 
-bboxArr=(`echo "$data" | tail -n +2 | sed 's/^[ ]*//' | cut -d\  -f2`)
-colorArr=(`echo "$data" | tail -n +2 | sed 's/^[ ]*//' | cut -d\  -f5`)
-num=${#bboxArr[*]}
+wwArr=(`echo "$data" | tail -n +2 | tr -cs "0-9.,\(\)\n" " " | awk '{print $2}'`)
+hhArr=(`echo "$data" | tail -n +2 | tr -cs "0-9.,\(\)\n" " " | awk '{print $3}'`)
+xoArr=(`echo "$data" | tail -n +2 | tr -cs "0-9.,\(\)\n" " " | awk '{print $4}'`)
+yoArr=(`echo "$data" | tail -n +2 | tr -cs "0-9.,\(\)\n" " " | awk '{print $5}'`)
+colorArr=(`echo "$data" | tail -n +2 | tr -cs "0-9.,gray\(\)\n" " " | awk '{print $8}'`)
+num=${#wwArr[*]}
 #echo $num
+
+# do sorting if specified
+if [ "$sortval" != "" ]; then
+	# build dataArr and sort it
+	# note new line before last quote so have list for sorting
+	# add rounded points for sorting
+	nearest=$sortval
+	for((i=0; i<num; i++)); do
+		xx=${xoArr[$i]}
+		yy=${yoArr[$i]}
+		xr=`convert xc: -format "%[fx:$nearest*round($xx/$nearest)]" info:`
+		yr=`convert xc: -format "%[fx:$nearest*round($yy/$nearest)]" info:`
+		dataArr[$i]="${wwArr[$i]} ${hhArr[$i]} ${xoArr[$i]} ${yoArr[$i]} ${colorArr[$i]} $xr $yr
+"
+		#echo ${dataArr[$i]}
+	done
+	OLDIFS=$IFS
+	IFS=$'\n'
+	sortArr=(`echo "${dataArr[*]}" | sort -n -k7,7 -k6,6`)
+	IFS=$OLDIFS
+	for((i=0; i<num; i++)); do
+		#echo "${sortArr[$i]}"
+		wwArr[$i]=`echo ${sortArr[$i]} | cut -d\  -f1`
+		hhArr[$i]=`echo ${sortArr[$i]} | cut -d\  -f2`
+		xoArr[$i]=`echo ${sortArr[$i]} | cut -d\  -f3`
+		yoArr[$i]=`echo ${sortArr[$i]} | cut -d\  -f4`
+		colorArr[$i]=`echo ${sortArr[$i]} | cut -d\  -f5`
+	done
+fi
 
 # abort if too many objects
 # subtract 1 for background
@@ -436,55 +597,60 @@ if [ "$threshold" != "" ]; then
 	[ $numm1 -gt $threshold ] && errMsg "--- TOO MANY OBJECTS DETECTED ---"
 fi
 
+if [ "$vc" = "yes" ]; then
+	repaging=""
+else
+	repaging="+repage"
+fi
+#echo "repaging=$repaging;"
+
 echo ""
 k=0
-if [ $unrotate -eq 1 -o $unrotate -eq 3 ]; then
-	for ((i=0; i<num; i++)); do
-		color="${colorArr[$i]}"
-		if [ "$color" != "gray(0)" ]; then
-			echo "Processing Image $k"
-			kk=`printf "%03d" "$k"`
-			if [ $extend -eq 0 ]; then
-				echo "Bounding Box: ${bboxArr[$i]}"
-				echo ""
-				convert $tmpA1 -crop "${bboxArr[$i]}" +repage $derotate \
-					-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage \
-					"${outname}-${kk}.${suffix}"
-				k=$((k+1))
-			else
-				wh=`echo "${bboxArr[$i]}" | cut -d+ -f1`
-				xoff=`echo "${bboxArr[$i]}" | cut -d+ -f2`
-				yoff=`echo "${bboxArr[$i]}" | cut -d+ -f3`
-				wd=`echo "$wh" | cut -dx -f1`
-				ht=`echo "$wh" | cut -dx -f2`
-				wd=$((wd+2*extend))
-				ht=$((ht+2*extend))
-				offx=$((offx-extend))
-				offy=$((offy-extend))
-				echo "Bounding Box: ${wd}x${ht}+${offx}+${offy}"
-				echo ""
-				convert $tmpA1 -crop ${wd}x${ht}+${offx}+${offy} +repage $derotate \
-					-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage \
-					"${outname}-${kk}.${suffix}"
-				k=$((k+1))
-			fi
+for ((i=0; i<num; i++)); do
+	color="${colorArr[$i]}"
+	if [ "$color" != "gray(0)" ]; then
+		echo "Processing Image $k"
+		kk=`printf "%03d" "$k"`
+		offx=${xoArr[$i]}
+		offy=${yoArr[$i]}
+		wd=${wwArr[$i]}
+		ht=${hhArr[$i]}
+		if [ "$resize" != "" ]; then
+				wd=`convert xc: -format "%[fx:round($wd*100/$resize)+2*$extend]" info:`
+				ht=`convert xc: -format "%[fx:round($ht*100/$resize)+2*$extend]" info:`
+				offx=`convert xc: -format "%[fx:round($offx*100/$resize)-$extend]" info:`
+				offy=`convert xc: -format "%[fx:round($offy*100/$resize)-$extend]" info:`
+			img=$tmpA4
+		else
+			wd=$((wd+2*extend))
+			ht=$((ht+2*extend))
+			offx=$((offx-extend))
+			offy=$((offy-extend))
+			img=$tmpA1
 		fi
-	done
-elif [ $unrotate -eq 2 ]; then
-	for ((i=0; i<num; i++)); do
-		color="${colorArr[$i]}"
-		if [ "$color" != "gray(0)" ]; then
-			echo "Processing Image $k"
-			kk=`printf "%03d" "$k"`
-			echo "Bounding Box: ${bboxArr[$i]}"
-			echo ""
-			convert $tmpA1 -crop "${bboxArr[$i]}" +repage \
+		echo "Initial Crop Box: ${wd}x${ht}+${offx}+${offy}"
+		echo ""
+		if [ $unrotate -eq 3 ]; then
+			convert $img -crop ${wd}x${ht}+${offx}+${offy} $repaging $tmpA3
+		elif [ $unrotate -eq 1 ]; then
+			convert $img -crop ${wd}x${ht}+${offx}+${offy} +repage $derotate \
+				-bordercolor "$bcolor" -border 2 -fuzz ${fuzzval}% -trim +repage $tmpA3
+		elif [ $unrotate -eq 2 ]; then
+			convert $img -crop ${wd}x${ht}+${offx}+${offy} +repage \
 				-fuzz ${fuzzval}% -trim miff:- | \
-				unrotate -f ${fuzzval}% - "${outname}-${kk}.${suffix}"
-			k=$((k+1))
+				unrotate -C "$bcolor" -f ${fuzzval}% - $tmpA3
 		fi
-	done
-fi
+		if [ "$innertrim" = "yes" ]; then
+			mextend=-$extend
+			autotrim -m inner -f $fuzzval -C "$bcolor" -l $mextend -t $mextend \
+				-r $extend -b $extend $tmpA3 ${outname}-${kk}.${suffix}
+			echo ""
+		else
+			convert $tmpA3 ${outname}-${kk}.${suffix}
+		fi
+		k=$((k+1))
+	fi
+done
 echo ""
 
 exit 0
